name: betchya
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: 3.3.10

dependencies:
  amplify_flutter: ^1.0.0
  amplify_api: ^1.0.0
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  crypto: ^3.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_facebook_auth: ^5.0.8
  flutter_localizations:
    sdk: flutter
  go_router: ^10.1.2
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  graphql_flutter: ^5.1.2
  http: ^0.13.5
  intl: ^0.18.0
  line_awesome_flutter: ^2.0.0
  marquee: ^2.2.3
  passwordfield: ^0.1.0
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^4.3.0
  smooth_page_indicator: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
